var myPolygons, key, areaUrl;

function featureSaveName(id, name) {
  $.each(myPolygons._layers, function(lid, layer) {
    if (myPolygons._layers[lid].feature.properties.id == id) {
      myPolygons._layers[lid].feature.properties.name = name;
      myPolygons._layers[lid].bindPopup('Navn: <input name="'+id+'" type="text" value="'+name+'" onchange="featureSaveName(this.name, this.value)"><button>Lagre</button>');
      myPolygons._layers[lid].closePopup();
      var data = {'name': name, 'geom': latlngsToString(myPolygons._layers[lid]._latlngs)};
      $.post(areaUrl + '?key=' + key + '&method=post&id='+id+'&callback=?', data, function(data) {
        // return myPolygons.addData(data);
      },'jsonp');
    }
  });
}

function latlngsToString(latlngs) {
  var str = '';
  for (var i = 0; i < latlngs.length; i++) {
    str += (i > 0 ? ',' : '') + latlngs[i].lng + ' ' + latlngs[i].lat;
  }
  return str + ',' + latlngs[0].lng + ' ' + latlngs[0].lat;
}


// Generated by CoffeeScript 1.4.0
(function() {
  "use strict";
  jQuery(function($) {    
    var topo, map, otherPolygons, drawControl;
    
    key = window.location.hash.substr(1);
    areaUrl = 'http://www2.turistforeningen.no/admin/ajax/area.php';
    topo = L.tileLayer('http://opencache.statkart.no/gatekeeper/gk/gk.open_gmaps?layers=topo2&zoom={z}&x={x}&y={y}', {
      maxZoom: 16,
      attribution: '<a href="http://www.statkart.no/">Statens kartverk</a>'
    });
    map = new L.Map('map', {layers: [topo], center: new L.LatLng(61.5, 9), zoom: 7 });
    
    otherPolygons = L.geoJson(null, {
      style: function (feature) {
    		return {color: 'blue'};
    	},
      onEachFeature: function(feature, layer) {
        feature.properties.name = $("<div/>").html(feature.properties.name).text();
        layer.bindPopup(feature.properties.name);
        return true;
      }
    }).addTo(map);
    
    myPolygons = L.geoJson(null, {
      style: function (feature) {
    		return {color: 'green'};
    	},
      onEachFeature: function(feature, layer) {
        feature.properties.name = $("<div/>").html(feature.properties.name).text();
        layer.bindPopup('Navn: <input name="'+feature.properties.id+'" type="text" value="'+feature.properties.name+'" onchange="featureSaveName(this.name, this.value)"><button>Lagre</button>');
        return true;
      }
    }).addTo(map);
    
    $.getJSON(areaUrl + '?key=' + key + '&callback=?', function(data) {
      for (var i = 0; i < data.features.length; i++) {
        if (data.features[i].properties.edit) {
          myPolygons.addData(data.features[i]);
        } else {
          otherPolygons.addData(data.features[i]);
        }
      }
    });
        
    drawControl = new L.Control.Draw({
      draw: {
        position  : 'topleft',
        polyline  : null,
        circle    : null,
        rectangle : null,
        marker    : null,
        polygon: {
          title: 'Nytt område',
          allowIntersection: false,
          drawError: {
            color: '#b00b00',
            opacity: 0.8,
            timeout: 1000
          },
        }
      },
      edit: {
        featureGroup: myPolygons,
        edit: {
          selectedPathOptions: {
            color: 'red',
            opacity: 0.8
          }
        }
      }
    });
    map.addControl(drawControl);
    
    map.on('draw:created', function (e) {
      var geom, name;
      
      name = 'Uten navn';
      geom = latlngsToString(e.layer._latlngs);
      
      $.post(areaUrl + '?key=' + key + '&method=post&callback=?', {'name': name, 'geom': geom}, function(data) {
        return myPolygons.addData(data);
      },'jsonp');
    });
    
    map.on('draw:deleted', function (e) {
      e.layers.eachLayer(function (layer) {
        var id;
        
        id = layer.feature.properties.id;
        
        $.get(areaUrl + '?key=' + key + '&method=delete&id='+id+'&callback=?', function(data) {
          console.log(data);
        },'jsonp');
      });
    });
    
    map.on('draw:edited', function (e) {
      e.layers.eachLayer(function (layer) {
        var id, name, geom;
        
        id = layer.feature.properties.id;
        name = layer.feature.properties.name;
        geom = latlngsToString(layer._latlngs);
        
        $.post(areaUrl + '?key=' + key + '&method=post&id='+id+'&callback=?', {'name': name, 'geom': geom}, function(data) {
          // return myPolygons.addData(data);
        },'jsonp');
      });
    });    
  });
}).call(this);
