// Generated by CoffeeScript 1.4.0
(function() {
  "use strict";
  jQuery(function($) {
    var topo, map, drawnItems, drawControl;
    
    topo = L.tileLayer('http://opencache.statkart.no/gatekeeper/gk/gk.open_gmaps?layers=topo2&zoom={z}&x={x}&y={y}', {
      maxZoom: 16,
      attribution: '<a href="http://www.statkart.no/">Statens kartverk</a>'
    });
    
    map = new L.Map('map', {layers: [topo], center: new L.LatLng(61.5, 9), zoom: 7 });
    
    L.marker([62.4717237147587, 6.2841796875]).addTo(map);
    
    drawnItems = L.geoJson(null, {
      onEachFeature: function(feature, layer) {
        console.log(feature, layer);
        return true;
      }
    }).addTo(map);
    
    $.getJSON('http://www2.turistforeningen.no/admin/ajax/area.php', function(data) {
      console.log(data.features);
      return drawnItems.addData(data);
    });
        
    drawControl = new L.Control.Draw({
      draw: {
        position  : 'topleft',
        polyline  : null,
        circle    : null,
        rectangle : null,
        marker    : null,
        polygon: {
          title: 'Marker område!',
          allowIntersection: false,
          drawError: {
            color: '#b00b00',
            timeout: 1000
          },
          shapeOptions: {
            color: '#0033ff',
            opacity: 0.5
          }
        }
      },
      edit: {
        featureGroup: drawnItems
      }
    });
    map.addControl(drawControl);
    
    map.on('draw:created', function (e) {
      /*
       * layer = e.layer
       * type = e.layerType
       */
      console.log(e);
      // e.layer.bindPopup('Navn: <input type="text" value="Mitt område"> <button>Lagre</button>');
      drawnItems.addLayer(e.layer);
      // open popup can happen after feature has been added to map
      // e.layer.openPopup(); // @todo find middle point
    });
    
    map.on('draw:edited', function (e) {
      var layers = e.layers;
      var countOfEditedLayers = 0;
      layers.eachLayer(function(layer) {
        countOfEditedLayers++;
      });
      console.log("Edited " + countOfEditedLayers + " layers");
    });
  });
}).call(this);
