// Generated by CoffeeScript 1.4.0
(function() {
  "use strict";
  jQuery(function($) {
    var topo, map, drawnItems, drawControl;
    
    topo = L.tileLayer('http://opencache.statkart.no/gatekeeper/gk/gk.open_gmaps?layers=topo2&zoom={z}&x={x}&y={y}', {
      maxZoom: 16,
      attribution: '<a href="http://www.statkart.no/">Statens kartverk</a>'
    });
    
    map = new L.Map('map', {layers: [topo], center: new L.LatLng(61.5, 9), zoom: 7 });
    
    drawnItems = L.geoJson(null, {
      onEachFeature: function(feature, layer) {
        return true;
      }
    }).addTo(map);
    
    $.getJSON('http://www2.turistforeningen.no/admin/ajax/area.php?callback=?', function(data) {
      return drawnItems.addData(data);
    });
        
    drawControl = new L.Control.Draw({
      draw: {
        position  : 'topleft',
        polyline  : null,
        circle    : null,
        rectangle : null,
        marker    : null,
        polygon: {
          title: 'Nytt område',
          allowIntersection: false,
          drawError: {
            color: '#b00b00',
            timeout: 1000
          },
          shapeOptions: {
            color: '#0033ff',
            opacity: 0.5
          }
        }
      },
      edit: {
        featureGroup: drawnItems
      }
    });
    map.addControl(drawControl);
    
    map.on('draw:created', function (e) {
      var geom, name;
      
      name = 'Område uten navn';
      geom = latlngsToString(e.layer._latlngs);
      
      $.post('http://www2.turistforeningen.no/admin/ajax/area.php?method=post&callback=?', {'name': name, 'geom': geom}, function(data) {
        return drawnItems.addData(data);
      },'jsonp');
    });
    
    map.on('draw:edited', function (e) {
      e.layers.eachLayer(function (layer) {
        var id, name, geom;
        
        console.log(layer);
        
        id = layer.feature.properties.id;
        name = layer.feature.properties.name;
        geom = latlngsToString(layer._latlngs);
        
        $.post('http://www2.turistforeningen.no/admin/ajax/area.php?method=post&id='+id+'&callback=?', {'name': name, 'geom': geom}, function(data) {
          console.log(data);
          // return drawnItems.addData(data);
        },'jsonp');
        
        console.log(layer.feature);
      });
    });
    
    function coordsToString(coords) {
      var str = '';
      for (var i = 0; i < coords.length; i++) {
        str += (i > 0 ? ',' : '') + coords[i][0] + ' ' + coords[i][1];
      }
      return str + ',' + coords[0][0] + ' ' + coords[0][1];
    }
    
    function latlngsToString(latlngs) {
      var str = '';
      for (var i = 0; i < latlngs.length; i++) {
        str += (i > 0 ? ',' : '') + latlngs[i].lng + ' ' + latlngs[i].lat;
      }
      return str + ',' + latlngs[0].lng + ' ' + latlngs[0].lat;
    }
    
  });
}).call(this);
